CustomUserProject/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
urlpatterns = [
    path('admin/', admin.site.urls),
    #  path('/voice-subtitle', views.index, name='index'),
    path('', include('accounts.urls')),

    path('accounts', include('django.contrib.auth.urls')),
    # path('/voice-subtitle', views.upload_files, name='voice-subtitle'),
    path('submitSubtitle', views.submitSubtitle, name='submitSubtitle'),
    path('create-lead', views.edit_slides, name='create-lead'),
    path("upload_files",views.upload_files,name="upload_files"),
    path('download', views.download, name='download'),
    path('download_file/<str:filename>/', views.download_file, name='download_file'),
    path('music',views.music,name="music"),
    path('loading',views.loading,name="loading"),
    path("loadingMusic",views.loadingMusic,name="loadingMusic"),
    path("loadingforFileUpload",views.loadingforFileUpload,name="loadingforFileUpload"),
    path('checkEditing',views.checkEditing,name="checkEditing"),
    path('', include('payment.urls')),
    path("manageSubscription",views.manage_subscription,name="manage_subscription")
]

accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from .views import *

app_name = 'accounts'
urlpatterns = [
    path('accounts/signup', signup_page, name='signup'),
    path('accounts/resetpasswordform/<slug:uidb64>/<slug:token>/', reset_password_form, name='reset_password_form'),
    path('accounts/activate_account_page/<slug:uidb64>/<slug:token>/', activate_account_page, name='activate_account_page'),
    path('accounts/login/', login_page, name='login'),
    path('accounts/signupFreeTrial', signup_page_free_trial, name='signupfreetrial'),
    
    path('accounts/logout/', logout_view, name='logout'),
path('contact', send_contact_email, name='send_contact_email'),

    # Reset Passoword Urls
    path('accounts/reset-password',reset_password,name="reset_password"),
    path('accounts/password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name='accounts/password_reset_sent.html'),
         name='password_reset_done'),
    path('accounts/reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='accounts/password_reset_form.html'),
         name='password_reset_confirm'),
    path('accounts/reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset_done.html'),
         name='password_reset_complete'),
     path("",home_view,name="home"),

]


# To update password reset functionality

payment/urls.py
from django.urls import path
from . import views

urlpatterns = [
	path('product_page', views.product_page, name='product_page'),
	path('payment_successful', views.payment_successful, name='payment_successful'),
	path('payment_cancelled', views.payment_cancelled, name='payment_cancelled'),
	path('stripe_webhook', views.stripe_webhook, name='stripe_webhook'),
    path("buycoins",views.buy_coins,name="buy_coins"),
    path("manageboughtcoins",views.manage_bought_coins,name="manage_bought_coins"),
	path("updatesubscription",views.update_subscription,name="update_subscription"),
    path("upgradeplan",views.upgrade_plan,name="upgrade_plan"),
    
]

accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import ReadOnlyPasswordHashField
from django.views.decorators.csrf import csrf_exempt, csrf_protect
User = get_user_model()


class UserAdminCreationForm(forms.ModelForm):
    '''A form for creating new users. Includes all required fields plus
    repeated password'''
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Confirm Password', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('email',)

    def clean_password2(self): # checking that the two passwords match
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError('Passwords do not match')
        return password2

    def save(self, commit=True): # save he proovided password in hashed format
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password1'])
        if commit:
            user.save()
        return user


class UserAdminChangeForm(forms.ModelForm):
    ''' A form for updating users, includes all the fields on the user, but
    replaces the password fields with admin's password hash display field. '''

    password = ReadOnlyPasswordHashField()

    class Meta:
        model = User
        fields = ('email', 'password', 'is_active', 'admin')

    def clean_password(self):
        ''' Regardless of what the user provides retrun the initial value.
        This is done here rather than on the field, because the field does
        not have access to the initial value. '''
        return self.initial['password']


class LoginForm(forms.Form):
    email = forms.EmailField(label='Email', widget=forms.EmailInput(attrs={'class': 'form-input',
                                                                           'placeholder': 'Enter email'}))
    password = forms.CharField(label='Password', widget=forms.PasswordInput(attrs={'class': 'form-input',
                                                                                   'placeholder': 'Enter password'}))


class RegistrationForm(forms.ModelForm):
    '''A form for creating new users. Includes all required fields plus
    repeated password'''
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput(attrs={'class': 'form-input', 'placeholder': 'Enter password'}))
    password2 = forms.CharField(label='Confirm Password', widget=forms.PasswordInput(attrs={'class': 'form-input', 'placeholder': 'Confirm password'}))

    class Meta:
        model = User
        fields = ['email']
        widgets = {'email': forms.EmailInput(attrs={'class': 'form-input', 'placeholder': 'Enter Email'})}

    def clean_password2(self):  # checking that the two passwords match
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError('Passwords do not match')
        return password2

    def save(self, commit=True): # save the provided password in hashed format
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password1'])
        if commit:
            user.is_active = False
            user.save()
        return user

accounts/views.py
from datetime import timedelta

from django.conf import settings
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout, get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.sites.shortcuts import get_current_site
from django.core.exceptions import ObjectDoesNotExist
from django.shortcuts import render, redirect
from django.utils import timezone
from django.utils.encoding import force_str
from django.utils.http import urlsafe_base64_decode
from django.urls import reverse
from .forms import RegistrationForm, LoginForm
from .models import LoginAttempt, User
from .token import account_activation_token
from .decorators import unauthenticated_user
from .utils import retrieve_Number_of_coins,send_welcome_email_html,get_token,send_password_reset,send_client_message
from django.views.decorators.csrf import csrf_exempt, csrf_protect
import stripe
from django.http import JsonResponse
@csrf_exempt
@unauthenticated_user
def signup_page_free_trial(request):
    form = RegistrationForm()
    if request.method == 'POST':
        email=request.POST.get("email")
        username=request.POST.get("FullName")
        password=request.POST.get("password")
        Confirmpassword=request.POST.get("Confirmpassword")
        form=RegistrationForm(data={'email': email, 'password1': password, 'password2': Confirmpassword})
        if form.is_valid():
            user = form.save()
            user.set_coins(0)
            user.set_stripe_subscription_id("")
            user.set_subscription_active(False)
            user.username=username
            user.is_active = False
            user.save()
            token=get_token(user)

            send_welcome_email_html(user.email, user.username.split(" ")[0],settings.REDIRECT_DOMAIN+f"/accounts/activate_account_page/{token['uid']}/{token['token']}")
            login_attempt, created = LoginAttempt.objects.get_or_create(user=user)
            return redirect(reverse("accounts:login"))
        else:
            if form.errors:
                for field in form:
                    for error in field.errors:
                        messages.error(request, error)
            form = RegistrationForm()
            context = {
            'form': form}
            return render(request, 'accounts/signupfreetrial.html', context)

            

    if request.method == 'GET':
        context = {
            'form': form
        }
        print('aaaaaaaaaaa')
        return render(request, 'accounts/signupfreetrial.html', context)

@csrf_exempt
@unauthenticated_user
def signup_page(request):
    form = RegistrationForm()
    if request.method == 'POST':
        try:
            stripe.api_key = settings.STRIPE_SECRET_KEY_TEST
            checkout_session_id = request.GET.get('session_id', None)
            session = stripe.checkout.Session.retrieve(checkout_session_id)
            username=session.customer_details.name
            subscription_id=session.subscription
            payment_id=stripe.Subscription.retrieve(subscription_id).plan.id
        except:
            return redirect(reverse("accounts:login"))
        number_of_coin=(retrieve_Number_of_coins(payment_id,settings.PRODUCT_PRICE))
        email=request.POST.get("email")
        password=request.POST.get("password")
        Confirmpassword=request.POST.get("Confirmpassword")
        form=RegistrationForm(data={'email': email, 'password1': password, 'password2': Confirmpassword})
        if form.is_valid():
            user = form.save()
            user.set_coins(number_of_coin)
            user.set_stripe_subscription_id(subscription_id)
            user.set_subscription_active(True)
            user.username=username
           
            user.is_active = True
            user.save()
            token=get_token(user)
            send_welcome_email_html(user.email, user.username.split(" ")[0],settings.REDIRECT_DOMAIN+f"/accounts/activate_account_page/{token['uid']}/{token['token']}")
            login_attempt, created = LoginAttempt.objects.get_or_create(user=user)
            if login_attempt.login_attempts >= settings.MAX_LOGIN_ATTEMPTS:
                login_attempt.login_attempts = 0
                login_attempt.save()
                messages.success(request, 'Account restored, you can now proceed to login')
                return redirect(reverse("accounts:login"))
            else:
                messages.success(request, 'Thank you for confirming your email. You can now login.')
                return redirect(reverse("accounts:login"))
        else:
            if form.errors:
                for field in form:
                    for error in field.errors:
                        messages.error(request, error)
            form = RegistrationForm()
    if request.method == 'GET':
        try:

            stripe.api_key = settings.STRIPE_SECRET_KEY_TEST
            checkout_session_id = request.GET.get('session_id', None)
            session = stripe.checkout.Session.retrieve(checkout_session_id)
            username=session.customer_details.name
            subscription_id=session.subscription
            payment_id=stripe.Subscription.retrieve(subscription_id).plan.id
        except:
            return redirect(reverse("accounts:login"))
        context = {
            'form': form
        }
        return render(request, 'accounts/signup.html', context)

@csrf_exempt
@unauthenticated_user
def login_page(request):
    form=LoginForm()
    if request.method == 'POST':
        email = request.POST.get('email')
        password = request.POST.get('password')
        form=LoginForm(data={'email': email, 'password': password})
        if form.is_valid():
            now = timezone.now()
            try:
                _user = User.objects.get(email=email)
                login_attempt, created = LoginAttempt.objects.get_or_create(user=_user)  # get the user's login attempt
                if (login_attempt.timestamp + timedelta(seconds=settings.LOGIN_ATTEMPTS_TIME_LIMIT)) < now:
                    user = authenticate(request, username=email, password=password)
                    if user is not None:
                        login(request, user)
                        login_attempt.login_attempts = 0    # reset the login attempts
                        login_attempt.save()
                        return redirect(reverse("submitSubtitle"),context={"user":user})  # change expected_url in your project

                    else:
                        # if the password is incorrect, increment the login attempts and
                        # if the login attempts == MAX_LOGIN_ATTEMPTS, set the user to be inactive and send activation email
                        login_attempt.login_attempts += 1
                        login_attempt.timestamp = now
                        login_attempt.save()
                        if login_attempt.login_attempts == settings.MAX_LOGIN_ATTEMPTS:
                            _user.is_active = False
                            _user.save()
                            # send the re-activation email
                            mail_subject = "Account suspended"
                            current_site = get_current_site(request)
                            # send_user_email(_user, mail_subject, email, current_site, 'accounts/email_account_suspended.html')
                            messages.error(request, 'Account suspended, maximum login attempts exceeded. '
                                                    'Reactivation link has been sent to your email')
                        else:
                            messages.error(request, 'Incorrect email or password')
                        return redirect(settings.LOGIN_URL)
                else:
                    messages.error(request, 'Login failed, please try again')
                    return redirect(settings.LOGIN_URL)

            except ObjectDoesNotExist:
    
                messages.error(request, 'Incorrect email or password')

                return redirect(settings.LOGIN_URL)
        else:
            if form.errors:
                for field in form:
                    for error in field.errors:
                        messages.error(request, error)
    context = {'form': form}

    return render(request, 'accounts/login.html', context)


def activate_account_page(request, uidb64, token):
    User = get_user_model()
    try:
        uid = force_str(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        login_attempt, created = LoginAttempt.objects.get_or_create(user=user)
        if login_attempt.login_attempts >= settings.MAX_LOGIN_ATTEMPTS:
            login_attempt.login_attempts = 0
            login_attempt.save()
            messages.success(request, 'Account restored, you can now proceed to login')
        else:
            messages.success(request, 'Thank you for confirming your email. You can now login.')
        return redirect(reverse("accounts:login"))
    else:
        messages.error(request, 'Activation link is invalid!')

        return redirect(reverse("accounts:login"))


def logout_view(request):
    logout(request)
    return redirect(settings.LOGOUT_REDIRECT_URL)
def send_contact_email(request):
    if request.method=="POST":
        print(request.POST)
        try:
            print(send_client_message(request.POST['email'],request.POST["full_name"],request.POST["message"]))
            return JsonResponse({"result":"message sent"},status=200)
        except:
            return JsonResponse({"result":"message is invalid"},status=403)
def home_view(request):
    if request.method=="GET":
        return render(request,'accounts/index.html')
        
def reset_password(request):

templates/accounts/email_verification.html
{% autoescape off %}
Hi ,
Please click on the link to confirm your registration,
http://{{ domain }}{% url 'accounts:activate' uidb64=uid token=token %}
{% endautoescape %}

templates/accounts/login.html
{% extends 'accounts/base.html' %}
{% block content %}
{% load static %}
<header class="admin-header">
  <div class="container">
    <div class="header-two">
      <div class="vsl-logo text-center">
        <a href="{% url 'accounts:home' %}">
          <img src="{% static '/images/logo.svg' %}" class="img-fluid" alt="Logo" />
        </a>
      </div>
    </div>
  </div>
</header>
<section class="login-sec">
    <div class="login-container">
        <!-- Logo Section -->
        <div class="vsl-logo text-center">
            <a href="{% url 'accounts:home' %}">
                <img src="{% static 'images/logo-dark.svg' %}" alt="LeadMaker Logo">
            </a>
        </div>

        <!-- Title -->
        <h5 class="login-title text-center">Sign in</h5>

        <!-- Login Form -->
        <form method="POST" id="login-form" class="form-block">
            {% csrf_token %}
            
            <div class="mb-3">
                <label for="email"  style="font-size: 1.8rem; font-weight: 600; color: #344054; margin-bottom: 9px; font-family: 'Plus Jakarta Sans', sans-serif;" >Email address:</label>
                <input type="email" name="email" value="{{ form.email.value|default:'' }}" placeholder="Email" class="form-control" id="email" aria-describedby="emailHelp">
            </div>

            <!-- Password Input -->
            <div class="mb-3">
                <label for="password" style="font-size: 1.8rem; font-weight: 600; color: #344054; margin-bottom: 9px; font-family: 'Plus Jakarta Sans', sans-serif;">Password:</label>
                <div class="pwd-input">
                    <input type="password" name="password" placeholder="Password" class="form-control" id="password">
                    <span class="show-icn" onclick="togglePasswordVisibility('password')">
                        <img src="{% static 'images/eye.svg' %}" alt="Toggle Password Visibility">
                    </span>
                </div>
                <a href="{% url 'accounts:reset_password' %}" class="forget-login">Forgot password?</a>
            </div>

            <!-- Submit Button -->
            <button type="submit" class="btn btn-primary get-start">Sign in</button>
        </form>

    </div>
        <script>
    function togglePasswordVisibility(id) {
        const passwordField = document.getElementById(id);
        const isPasswordVisible = passwordField.type === "text";
        passwordField.type = isPasswordVisible ? "password" : "text";
    }
</script>
</section>

{% endblock content %}

templates/accounts/password_reset.html
{% extends 'accounts/base.html' %}
{% block content %}
{% load static %}
<header class="admin-header">
  <div class="container">
    <div class="header-two">
      <div class="vsl-logo text-center">
        <a href="{% url 'accounts:home' %}">
          <img src="{% static '/images/logo.svg' %}" class="img-fluid" alt="Logo" />
        </a>
      </div>
    </div>
  </div>
</header>
<section class="login-sec">
    <div class="register-container">
        <!-- Logo Section -->
        <div class="vsl-logo text-center">
            <a href="{% url 'accounts:home' %}">
                <img src="{% static 'images/logo-dark.svg' %}" alt="LeadMaker Logo">
            </a>
        </div>

        <!-- Title -->
        <div class="payment-message">
            <h1>Fill your Email linked to your Account</h1>
            <p>After submitting, remember to check your email inbox to finalize your password reset!</p>
        </div>

        <!-- Login Form -->
        <form method="POST" id="login-form" class="form-block">
            {% csrf_token %}
            
            <div class="mb-3">
                <label for="email"  style="font-size: 1.8rem; font-weight: 600; color: #344054; margin-bottom: 9px; font-family: 'Plus Jakarta Sans', sans-serif;" >Email address:</label>
                <input type="email" name="email" value="{{ form.email.value|default:'' }}" placeholder="Email" class="form-control" id="email" aria-describedby="emailHelp">
            </div>
            <!-- Submit Button -->
            <button type="submit" class="btn btn-primary get-start">Reset Password</button>
        </form>

    </div>
        <script>
    function togglePasswordVisibility(id) {
        const passwordField = document.getElementById(id);
        const isPasswordVisible = passwordField.type === "text";
        passwordField.type = isPasswordVisible ? "password" : "text";
    }
</script>
</section>

{% endblock content %}

templates/accounts/password_reset_form.html
{% extends 'accounts/base.html' %}
{% block content %}
{% load static %}
<header class="admin-header">
  <div class="container">
    <div class="header-two">
      <div class="vsl-logo text-center">
        <a href="{% url 'accounts:home' %}">
          <img src="{% static '/images/logo.svg' %}" class="img-fluid" alt="Logo" />
        </a>
      </div>
    </div>
  </div>
</header>
<section class="login-sec">
    <div class="register-container">
        <!-- Logo Section -->
        <div class="vsl-logo text-center">
            <a href="{% url 'accounts:home' %}">
                <img src="{% static 'images/logo-dark.svg' %}" alt="LeadMaker Logo">
            </a>
        </div>

        <!-- Title -->
        <div class="payment-message">
            <h1>Reset Your password </h1>
        </div>
        <!-- Login Form -->
        <form method="POST" id="login-form" class="form-block">
            {% csrf_token %}
            <!-- Password Input -->
            <div class="mb-3">
                <label for="password" style="font-size: 1.8rem; font-weight: 600; color: #344054; margin-bottom: 12px; font-family: 'Plus Jakarta Sans', sans-serif;">Password:</label>
                <div class="pwd-input">
                    <input type="password" name="password" placeholder="Password" class="form-control" id="password">
                    <span class="show-icn" onclick="togglePasswordVisibility('password')">
                        <img src="{% static 'images/eye.svg' %}" alt="Toggle Password Visibility">
                    </span>
                </div>
            </div>
            <div class="mb-3" >
                <label for="Confirmpassword" style="font-size: 1.8rem; font-weight: 600; color: #344054; margin-bottom: 12px; font-family: 'Plus Jakarta Sans', sans-serif;">Confirm Password:</label>
                <div class="pwd-input">
                    <input type="password" name="Confirmpassword" placeholder="Confirm Password" class="form-control" id="Confirmpassword">
                </div>
            </div>

            <!-- Submit Button -->
            <button  type="submit" class="btn btn-primary get-start" style="margin-top: 30px">Reset Password</button>
        </form>

    </div>
    <script>
    function togglePasswordVisibility(id) {
        const passwordField = document.getElementById(id);
        const isPasswordVisible = passwordField.type === "text";
        passwordField.type = isPasswordVisible ? "password" : "text";
    }
</script>
</section>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>



{% endblock content %}

templates/accounts/signup.html
{% extends 'accounts/base.html' %}
{% block content %}
{% load static %}
<header class="admin-header">
  <div class="container">
    <div class="header-two">
      <div class="vsl-logo text-center">
        <a href="{% url 'accounts:home' %}">
          <img src="{% static '/images/logo.svg' %}" class="img-fluid" alt="Logo" />
        </a>
      </div>
    </div>
  </div>
</header>
<section class="login-sec">
    <div class="register-container">
        <!-- Logo Section -->
        <div class="vsl-logo text-center">
            <a href="{% url 'accounts:home' %}">
                <img src="{% static 'images/logo-dark.svg' %}" alt="LeadMaker Logo">
            </a>
        </div>

        <!-- Title -->
        <div class="payment-message">
            <h1>Your Payment Has Been Completed Successfully.</h1>
            <p>Set Your Email And Password For Your Account Below</p>
        </div>
        <!-- Login Form -->
        <form method="POST" id="login-form" class="form-block">
            {% csrf_token %}
            <div class="mb-3">
                <label for="email" style="font-size: 1.8rem; font-weight: 600; color: #344054; margin-bottom: 12px; font-family: 'Plus Jakarta Sans', sans-serif;">Email address:</label>
                <input type="email" name="email" value="{{ form.email.value|default:'' }}" placeholder="Email" class="form-control" id="email" aria-describedby="emailHelp">
            </div>

            <!-- Password Input -->
            <div class="mb-3">
                <label for="password" style="font-size: 1.8rem; font-weight: 600; color: #344054; margin-bottom: 12px; font-family: 'Plus Jakarta Sans', sans-serif;">Password:</label>
                <div class="pwd-input">
                    <input type="password" name="password" placeholder="Password" class="form-control" id="password">
                    <span class="show-icn" onclick="togglePasswordVisibility('password')">
                        <img src="{% static 'images/eye.svg' %}" alt="Toggle Password Visibility">
                    </span>
                </div>
            </div>
            <div class="mb-3" >
                <label for="Confirmpassword" style="font-size: 1.8rem; font-weight: 600; color: #344054; margin-bottom: 12px; font-family: 'Plus Jakarta Sans', sans-serif;">Confirm Password:</label>
                <div class="pwd-input">
                    <input type="password" name="Confirmpassword" placeholder="Confirm Password" class="form-control" id="Confirmpassword">
                </div>
            </div>

            <!-- Submit Button -->
            <button  type="submit" class="btn btn-primary get-start" style="margin-top: 30px">Sign in</button>
        </form>

    </div>
    <script>
    function togglePasswordVisibility(id) {
        const passwordField = document.getElementById(id);
        const isPasswordVisible = passwordField.type === "text";
        passwordField.type = isPasswordVisible ? "password" : "text";
    }
</script>
</section>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>



{% endblock content %}

templates/accounts/signupfreetrial.html
{% extends 'accounts/base.html' %}
{% block content %}
{% load static %}
<header class="admin-header">
  <div class="container">
    <div class="header-two">
      <div class="vsl-logo text-center">
        <a href="{% url 'accounts:home' %}">
          <img src="{% static '/images/logo.svg' %}" class="img-fluid" alt="Logo" />
        </a>
      </div>
    </div>
  </div>
</header>
<section class="login-sec">
    <div class="register-container">
        <!-- Logo Section -->
        <div class="vsl-logo text-center">
            <a href="{% url 'accounts:home' %}">
                <img src="{% static 'images/logo-dark.svg' %}" alt="LeadMaker Logo">
            </a>
        </div>

        <!-- Title -->
        <div class="payment-message">
            <h1>Sign up</h1>
        </div>
        <!-- Login Form -->
        <form method="POST" id="login-form" class="form-block">
            {% csrf_token %}
            <div class="mb-3">
                <label for="FullName" style="font-size: 1.8rem; font-weight: 600; color: #344054; margin-bottom: 12px; font-family: 'Plus Jakarta Sans', sans-serif;">Name :</label>
                <input type="text" name="FullName" value="{{ form.email.value|default:'' }}" placeholder="FullName" class="form-control" id="FullName" aria-describedby="FullName">
            </div>
            <div class="mb-3">
                <label for="email" style="font-size: 1.8rem; font-weight: 600; color: #344054; margin-bottom: 12px; font-family: 'Plus Jakarta Sans', sans-serif;">Email address:</label>
                <input type="email" name="email" value="{{ form.email.value|default:'' }}" placeholder="Email" class="form-control" id="email" aria-describedby="emailHelp">
            </div>

            <!-- Password Input -->
            <div class="mb-3">
                <label for="password" style="font-size: 1.8rem; font-weight: 600; color: #344054; margin-bottom: 12px; font-family: 'Plus Jakarta Sans', sans-serif;">Password:</label>
                <div class="pwd-input">
                    <input type="password" name="password" placeholder="Password" class="form-control" id="password">
                    <span class="show-icn" onclick="togglePasswordVisibility('password')">
                        <img src="{% static 'images/eye.svg' %}" alt="Toggle Password Visibility">
                    </span>
                </div>
            </div>
            <div class="mb-3" >
                <label for="Confirmpassword" style="font-size: 1.8rem; font-weight: 600; color: #344054; margin-bottom: 12px; font-family: 'Plus Jakarta Sans', sans-serif;">Confirm Password:</label>
                <div class="pwd-input">
                    <input type="password" name="Confirmpassword" placeholder="Confirm Password" class="form-control" id="Confirmpassword">
                </div>
            </div>

            <!-- Submit Button -->
            <button  type="submit" class="btn btn-primary get-start" style="margin-top: 30px">Sign up</button>
        </form>

    </div>
    <script>
    function togglePasswordVisibility(id) {
        const passwordField = document.getElementById(id);
        const isPasswordVisible = passwordField.type === "text";
        passwordField.type = isPasswordVisible ? "password" : "text";
    }
</script>
</section>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>



{% endblock content %}